

it: FORCE
	latexmk -pdf Dynamic_Problem

spell:
	aspell check --lang=en Dynamic_Problem.tex

clean:
	$(RM) Dynamic_Problem.pdf
	$(RM) *.aux
	$(RM) *.bak
	$(RM) *.log	
	$(RM) *.fdb_latexmk
	$(RM) *.fls	

FORCE:

