#!/bin/sh

echo Adhesion_Facotr.h
diff Adhesion_Factor.h $DELIVERY/Adhesion_Factor/Adhesion_Factor.h
echo Adhesion_Factor_Encoder.h
diff Adhesion_Factor_Encoder.h $DELIVERY/Adhesion_Factor/Adhesion_Factor_Encoder.h
echo Adhesion_Factor_Decoder.h
diff Adhesion_Factor_Decoder.h $DELIVERY/Adhesion_Factor/Adhesion_Factor_Decoder.h
echo Adhesion_Factor_Init.h
diff Adhesion_Factor_Init.h $DELIVERY/Adhesion_Factor/Adhesion_Factor_Init.h
echo Adhesion_Factor_UpperBitsNotSet.h
diff Adhesion_Factor_UpperBitsNotSet.h $DELIVERY/Adhesion_Factor/Adhesion_Factor_UpperBitsNotSet.h
echo Adhesion_Factor_Encoder.c
diff Adhesion_Factor_Encoder.c $DELIVERY/Adhesion_Factor/Adhesion_Factor_Encoder.c
echo Adhesion_Factor_Decoder.c
diff Adhesion_Factor_Decoder.c $DELIVERY/Adhesion_Factor/Adhesion_Factor_Decoder.c
echo Adhesion_Factor_Init.c
diff Adhesion_Factor_Init.c $DELIVERY/Adhesion_Factor/Adhesion_Factor_Init.c
echo Adhesion_Factor_UpperBitsNotSet.c
diff Adhesion_Factor_UpperBitsNotSet.c $DELIVERY/Adhesion_Factor/Adhesion_Factor_UpperBitsNotSet.c
