
include ../Makefile.template

VPATH = ../Bitwalker
CPPFLAGS += -I../Bitwalker

obj: Package_Foo_Init.o Package_Foo_Decoder.o

report-wp:\
	Package_Foo_Init.report-wp\
	Package_Foo_Decoder.report-wp\
