
include ../Makefile.template

VPATH = ../Bitwalker
CPPFLAGS += -I../Bitwalker


obj:\
	Package_Foo_Init.o\
     	Package_Foo_UpperBitsNotSet.o\
     	Package_Foo_Decoder.o\
     	Package_Foo_Encoder.o\


report-wp:\
	Package_Foo_Init.report-wp\
	Package_Foo_UpperBitsNotSet.report-wp\
	Package_Foo_Decoder.report-wp\
	Package_Foo_Encoder.report-wp\

